name: First Workflow

on:
  push:

jobs:
  hello:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: hello workflow
        run: echo "hello from the github!"

      - name: list files
        run: ls -la

#      - name: mvn build
#        run: mvn clean package