name: First Workflow

on:
  push:

jobs:
  hello:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repository
        run: actions/checkout@v4

      - name: hello workflow
        run: echo "hello from the github!"